name: flutter_bloc_advance
description: flutter_bloc_advance
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_theme:
  cupertino_icons:
  flutter_bloc:
  equatable:
  flutter_secure_storage:
  dart_json_mapper:
  dart_json_mapper_flutter:
  http:
  device_preview:
  getwidget:
  flutter_form_builder:
  form_builder_validators:
  intl: ^0.18.1
  string_2_icon:

dependency_overrides:
  reflectable:
  intl:
  glob:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints:
  build_runner: any



flutter_intl:
  enabled: true
  class_name: S
  main_locale: en

flutter_secure_storage:
  enabled: true
  class_name: SecureStorage
  main_locale: en

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/Icon-192.png
    - assets/mock/users.json
    - assets/mock/tasks.json
    - assets/mock/id_token.json
    - assets/mock/menu.json

