name: flutter_bloc_advance
description: Flutter Bloc Advance Template
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: '3.24.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_theme:
  cupertino_icons:
  flutter_bloc:
  equatable:
  pdf:
  printing:
  dart_json_mapper:
  expansion_tile_card:
  http:
  device_preview:
  getwidget:
  flutter_form_builder:
  get:
  form_builder_validators:
  intl:
  string_2_icon:
  shared_preferences:
  intl_utils:
  pattern_formatter:
  http_certificate_pinning:
  bloc_concurrency:
  modbus_client_tcp:
  custom_navigation_bar:
  flutter_inappwebview:

dependency_overrides:
  reflectable:
  intl:
  glob:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:


flutter_secure_storage:
  enabled: true
  class_name: SecureStorage
  main_locale: en

flutter:
  uses-material-design: true
  assets:
    - assets/mock/
    - assets/images/

